export const places: { [city: string]: { [district: string]: string[] } } = {
    "Đà Nẵng": {
      "Hải Châu": [
        "An Hải Bắc",
        "An Hải Đông",
        "Bình Hiệp",
        "Bình Trưng Tây",
        "Cẩm Châu",
        "Hòa Khê",
        "Hòa Minh",
        "Hoài An",
        "Hoài Phước",
        "Kim Châu",
        "Lai Khê",
        "Mân Thái",
        "Nam Phước",
        "Thanh Khê Đông",
        "Thanh Khê Tây",
        "Vĩnh Trung",
      ],
      "Sơn Trà": [
        "An Hải Tây",
        "Apê Đắk",
        "Bắc Mỹ An",
        "Mân Quang",
        "Nại Hiên Đông",
        "Nại Hiên Tây",
        "Phước Hòa",
        "Thọ Quang",
        "Thọ Toán",
      ],
      "Ngũ Hành Sơn": [
        "Hòa Hải",
        "Hòa Hiệp Bắc",
        "Hòa Hiệp Nam",
        "Hòa Phước",
        "Lệ Hà",
        "Tam Thanh",
        "Vĩnh Hà",
        "Hòa Quý",
      ],
      "Liên Chiểu": [
        "Hòa Khê Đông",
        "Hòa Khê Tây",
        "Hòa Minh",
        "Hòa Phát",
        "Hòa Thọ",
        "Hưng Lộc",
        "Liên Chiểu",
        "Thanh Khê Đông",
        "Thanh Khê Tây",
      ],
      "Thanh Khê": [
        "An Khê",
        "Chính Mỹ",
        "Chúc Cứu",
        "Hòa An",
        "Hòa Khê Đông",
        "Hòa Khê Tây",
        "Thanh Khê Đông",
        "Thanh Khê Tây",
        "Vĩnh Trung",
      ],
      "Cẩm Lệ": [
        "Hòa An",
        "Hòa Phát",
        "Hòa Thọ",
        "Hòa Xuân",
        "Khuê Mỹ Đông",
        "Khuê Mỹ Tây",
        "Tam Hòa",
        "Tân An",
        "Thọ Quang",
      ],
      "Hòa Vang": [
        "Hòa Châu",
        "Hòa Phong",
        "Hòa Phú",
        "Hòa Nhơn",
        "Hoà Ninh",
        "Hoà Nhất",
        "Hoà Sơn",
        "Hoà Liên",
        "Hoà Khê",
        "Hoà Hiệp Bắc",
        "Hoà Hiệp Nam",
        "Hoà Phước",
        "Hoà Thọ",
        "Hoà Xuân",
        "Hoà An",
        "Khuê Mỹ Đông",
        "Khuê Mỹ Tây",
        "Tam Hòa",
        "Tân An",
        "Thọ Quang",
        "Vĩnh Hà",
        "Lệ Hà",
        "Hòa Hải",
      ],
    },
  };